-- 작업 리스트(재고확인 / 진열보충 / 이형포장 / 품절관리) + 통합 작업로그 테이블.
-- 전부 추가만 한다. 기존 테이블/함수는 건드리지 않는다.

create or replace function public.warehouse_kst_today()
returns date
language sql
stable
as $$
  select (now() at time zone 'Asia/Seoul')::date
$$;

-- ---------------------------------------------------------------------------
-- 통합 작업로그. items FK 없음(상품이 지워져도 이력 보존), 상품명/로케이션은 스냅샷.
-- ---------------------------------------------------------------------------
create table if not exists public.warehouse_action_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity text not null default '',
  entity_id text not null default '',
  work_date date,
  item_code text,
  item_name text not null default '',
  location_code text not null default '',
  detail jsonb not null default '{}'::jsonb,
  source text not null default 'web' check (source in ('web', 'mops', 'system')),
  actor_user_id uuid,
  actor_email text not null default '',
  actor_name text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists warehouse_action_logs_created_at_idx
  on public.warehouse_action_logs (created_at desc);

create index if not exists warehouse_action_logs_item_code_idx
  on public.warehouse_action_logs (item_code, created_at desc);

create index if not exists warehouse_action_logs_action_idx
  on public.warehouse_action_logs (action, created_at desc);

alter table public.warehouse_action_logs enable row level security;

-- ---------------------------------------------------------------------------
-- 재고확인 요청
-- ---------------------------------------------------------------------------
create table if not exists public.warehouse_stock_check_requests (
  id uuid primary key default gen_random_uuid(),
  check_date date not null,
  item_code text not null references public.items(code) on update cascade on delete cascade,
  item_name text not null default '',
  location_code text not null default '',
  db_stock integer,
  source text not null default 'item' check (source in ('auto_low_stock', 'item', 'irregular')),
  sources text[] not null default '{}'::text[],
  request_note text not null default '',
  status text not null default 'pending' check (status in ('pending', 'match', 'mismatch')),
  counted_qty integer check (counted_qty is null or counted_qty >= 0),
  mismatch_reason text not null default '',
  resolved boolean not null default false,
  resolved_note text not null default '',
  resolved_at timestamptz,
  resolved_by_user_id uuid,
  resolved_by_name text not null default '',
  checked_at timestamptz,
  checked_by_user_id uuid,
  checked_by_name text not null default '',
  requested_by_user_id uuid,
  requested_by_email text not null default '',
  requested_by_name text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists warehouse_stock_check_requests_pending_uidx
  on public.warehouse_stock_check_requests (check_date, item_code)
  where status = 'pending';

create index if not exists warehouse_stock_check_requests_date_idx
  on public.warehouse_stock_check_requests (check_date, item_code);

create index if not exists warehouse_stock_check_requests_item_code_idx
  on public.warehouse_stock_check_requests (item_code);

create index if not exists warehouse_stock_check_requests_open_mismatch_idx
  on public.warehouse_stock_check_requests (check_date)
  where status = 'mismatch' and not resolved;

drop trigger if exists warehouse_stock_check_requests_set_updated_at on public.warehouse_stock_check_requests;
create trigger warehouse_stock_check_requests_set_updated_at
before update on public.warehouse_stock_check_requests
for each row
execute function public.warehouse_set_updated_at();

alter table public.warehouse_stock_check_requests enable row level security;

-- ---------------------------------------------------------------------------
-- 진열보충 요청
-- ---------------------------------------------------------------------------
create table if not exists public.warehouse_display_requests (
  id uuid primary key default gen_random_uuid(),
  request_date date not null,
  item_code text not null references public.items(code) on update cascade on delete cascade,
  item_name text not null default '',
  location_code text not null default '',
  db_stock integer,
  source text not null default 'item' check (source in ('item', 'irregular')),
  sources text[] not null default '{}'::text[],
  request_note text not null default '',
  status text not null default 'open' check (status in ('open', 'done')),
  done_at timestamptz,
  done_by_user_id uuid,
  done_by_name text not null default '',
  requested_by_user_id uuid,
  requested_by_email text not null default '',
  requested_by_name text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists warehouse_display_requests_open_uidx
  on public.warehouse_display_requests (request_date, item_code)
  where status = 'open';

create index if not exists warehouse_display_requests_date_idx
  on public.warehouse_display_requests (request_date, item_code);

create index if not exists warehouse_display_requests_item_code_idx
  on public.warehouse_display_requests (item_code);

drop trigger if exists warehouse_display_requests_set_updated_at on public.warehouse_display_requests;
create trigger warehouse_display_requests_set_updated_at
before update on public.warehouse_display_requests
for each row
execute function public.warehouse_set_updated_at();

alter table public.warehouse_display_requests enable row level security;

-- ---------------------------------------------------------------------------
-- 이형포장 리스트 (MOPS 엑셀 출력 시 저장)
-- ---------------------------------------------------------------------------
create table if not exists public.warehouse_irregular_items (
  id uuid primary key default gen_random_uuid(),
  work_date date not null,
  batch_key text not null default '',
  item_code text not null references public.items(code) on update cascade on delete cascade,
  item_name text not null default '',
  location_code text not null default '',
  qty integer not null default 0,
  order_count integer not null default 0,
  mixed_order_count integer not null default 0,
  expected_box_count integer check (expected_box_count is null or expected_box_count >= 0),
  status text not null default '대기' check (status in ('대기', '작업중', '포장완료')),
  stale boolean not null default false,
  export_count integer not null default 1,
  last_exported_at timestamptz,
  status_changed_at timestamptz,
  status_changed_by_user_id uuid,
  status_changed_by_name text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists warehouse_irregular_items_batch_item_uidx
  on public.warehouse_irregular_items (work_date, batch_key, item_code);

create index if not exists warehouse_irregular_items_item_code_idx
  on public.warehouse_irregular_items (item_code);

drop trigger if exists warehouse_irregular_items_set_updated_at on public.warehouse_irregular_items;
create trigger warehouse_irregular_items_set_updated_at
before update on public.warehouse_irregular_items
for each row
execute function public.warehouse_set_updated_at();

alter table public.warehouse_irregular_items enable row level security;

-- ---------------------------------------------------------------------------
-- 품절관리 리스트
-- ---------------------------------------------------------------------------
create table if not exists public.warehouse_soldout_items (
  id uuid primary key default gen_random_uuid(),
  soldout_date date not null,
  item_code text not null references public.items(code) on update cascade on delete cascade,
  item_name text not null default '',
  location_code text not null default '',
  db_stock integer,
  source text not null default 'stock_check' check (source in ('stock_check', 'display')),
  sources text[] not null default '{}'::text[],
  source_ref_id uuid,
  status_at_add text not null default '',
  last_set_status text not null default '',
  last_set_at timestamptz,
  last_set_by_user_id uuid,
  last_set_by_name text not null default '',
  added_by_user_id uuid,
  added_by_email text not null default '',
  added_by_name text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists warehouse_soldout_items_date_item_uidx
  on public.warehouse_soldout_items (soldout_date, item_code);

create index if not exists warehouse_soldout_items_item_code_idx
  on public.warehouse_soldout_items (item_code);

drop trigger if exists warehouse_soldout_items_set_updated_at on public.warehouse_soldout_items;
create trigger warehouse_soldout_items_set_updated_at
before update on public.warehouse_soldout_items
for each row
execute function public.warehouse_set_updated_at();

alter table public.warehouse_soldout_items enable row level security;
