-- MOPS 2026 전용 테이블 15개 추가
-- items, daily_stock, warehouse_racks, warehouse_movements 는 기존 테이블을 그대로 사용

-- 1단계: 독립 테이블 (FK 없음)

create table if not exists public.marketplaces (
  key text primary key,
  display_name text not null,
  sort_order integer not null default 0,
  active boolean not null default true
);

create table if not exists public.orders (
  code text primary key,
  order_date date not null,
  payment_channel text,
  shipping_cost numeric,
  bank_fee numeric,
  exchange_rate numeric,
  final_amount numeric,
  memo text,
  tracking_number text,
  website_order_number text default 'No_data',
  shipping_status boolean default false
);

create table if not exists public.imports (
  code text primary key,
  import_date date,
  import_date_raw text,
  exchange_rate numeric,
  overseas_shipping_cost numeric,
  ocean_freight numeric,
  handling_charge numeric,
  customs_fee numeric,
  domestic_shipping_cost numeric,
  inspection_fee numeric,
  total_price numeric default 0,
  memo text
);

create table if not exists public.monthly_summary (
  id bigint generated by default as identity primary key,
  year_month_channel text not null unique,
  최종매출액 numeric not null default 0,
  최종정산액 numeric not null default 0,
  최종순이익 numeric not null default 0,
  최종위탁지불금액 numeric not null default 0,
  최종위탁마진 numeric not null default 0,
  최종셀링온마진 numeric not null default 0
);

create table if not exists public.packaging_type_list (
  id bigint generated by default as identity primary key,
  name text,
  boxtype text
);

create table if not exists public.customer_management (
  id bigint generated by default as identity primary key,
  cs_date timestamptz not null unique,
  cs_name text,
  cs_phone text,
  cs_mall text,
  cs_type text,
  procedure text,
  return_items text,
  resend_items text,
  cs_reason text,
  cs_reason_detail text
);

create table if not exists public.detailed_result (
  id bigint generated by default as identity primary key,
  year_month_channel text not null,
  주문번호 text,
  상품주문번호 text,
  주문자명 text,
  상품명 text,
  옵션명 text,
  주문수량 numeric,
  주문가격 numeric,
  수수료 numeric,
  기타수수료 numeric,
  입금액 numeric,
  배송비 numeric,
  배송비수수료 numeric,
  예상배송비 numeric,
  매칭상품코드 text,
  매칭상품명 text,
  매칭상품단가 numeric,
  매칭상품사이즈 bytea,
  매칭상품부피 numeric,
  상품원가 numeric,
  상품부피 numeric,
  상품마진 numeric,
  상품매출 numeric,
  정산비율 numeric,
  구분 text,
  위탁지불금액 numeric,
  위탁마진 numeric,
  셀링온마진 numeric
);

-- 2단계: items 의존 테이블

create table if not exists public.matching_lists (
  id bigint generated by default as identity primary key,
  match_text text not null,
  item_code text references public.items(code) on delete set null,
  "PCS" integer default 1
);

create table if not exists public.item_stocks (
  item_code text primary key references public.items(code) on delete cascade,
  stock_today integer not null default 0,
  stock_prev integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.listing_ids (
  id bigint generated by default as identity primary key,
  item_code text not null references public.items(code) on delete cascade,
  marketplace_key text not null references public.marketplaces(key),
  listing_id text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (item_code, marketplace_key, listing_id)
);

create table if not exists public.listing_links (
  id bigint generated by default as identity primary key,
  item_code text not null references public.items(code) on delete cascade,
  marketplace_key text not null references public.marketplaces(key),
  listing_id text,
  listing_url text,
  status text,
  updated_at timestamptz not null default timezone('utc', now()),
  remarks text,
  unique (item_code, marketplace_key)
);

-- 3단계: orders 의존 테이블

create table if not exists public.order_details (
  code text primary key,
  shipping_div text,
  bank_fee_div text,
  order_quantity integer,
  quantity_not_in_stock integer,
  input_unit_price numeric,
  total_volume numeric,
  shipping_cost numeric,
  bank_fee numeric,
  total_cost numeric,
  unit_price numeric,
  final_unit_price numeric,
  item_code text references public.items(code) on delete set null,
  order_code text references public.orders(code) on delete cascade
);

create table if not exists public.finance_1st (
  code text primary key,
  date date not null,
  description text,
  transaction_type text,
  transfer_amount numeric,
  bank_charge numeric,
  transfer_charge numeric,
  cable_charge numeric,
  agency_charge numeric,
  deposit_amount numeric,
  payment_amount numeric,
  exchange_rate numeric,
  order_code text references public.orders(code) on delete set null,
  legacy_order_code text,
  balance numeric
);

create table if not exists public.finance_2nd (
  code text primary key,
  date date not null,
  description text,
  transaction_type text,
  transfer_amount numeric,
  bank_charge numeric,
  transfer_charge numeric,
  cable_charge numeric,
  agency_charge numeric,
  deposit_amount numeric,
  payment_amount numeric,
  exchange_rate numeric,
  order_code text references public.orders(code) on delete set null,
  legacy_order_code text,
  balance numeric
);

-- 4단계: order_details / imports 의존 테이블

create table if not exists public.import_details (
  code text primary key,
  input_unit_price numeric,
  import_quantity integer,
  volume numeric,
  overseas_shipping_div text,
  inspection_fee_div text,
  import_tariff_rate numeric,
  import_surtax_rate numeric,
  overseas_shipping_cost numeric,
  ocean_freight numeric,
  handling_charge numeric,
  customs_fee numeric,
  domestic_shipping_cost numeric,
  inspection_fee numeric,
  import_tariff numeric,
  import_surtax numeric,
  total_import_price numeric,
  import_unit_price numeric,
  item_code text references public.items(code) on delete set null,
  import_code text references public.imports(code) on delete cascade,
  order_detail_code text references public.order_details(code) on delete set null
);

-- 인덱스

create index if not exists idx_mops_orders_date on public.orders(order_date, code);
create index if not exists idx_mops_orders_status on public.orders(shipping_status);
create index if not exists idx_mops_imports_date on public.imports(import_date, code);
create index if not exists idx_mops_finance1_date on public.finance_1st(date, code);
create index if not exists idx_mops_finance1_order on public.finance_1st(order_code);
create index if not exists idx_mops_finance2_date on public.finance_2nd(date, code);
create index if not exists idx_mops_finance2_order on public.finance_2nd(order_code);
create index if not exists idx_mops_matching_text on public.matching_lists(match_text);
create index if not exists idx_mops_listing_ids_item on public.listing_ids(item_code, marketplace_key);
create index if not exists idx_mops_listing_ids_lid on public.listing_ids(listing_id);
create index if not exists idx_mops_item_stocks_updated on public.item_stocks(updated_at);
create index if not exists idx_mops_detailed_result_ymc on public.detailed_result(year_month_channel);
create index if not exists idx_mops_customer_cs_date on public.customer_management(cs_date);

-- RLS 활성화 (postgres superuser는 자동으로 bypass)
alter table public.marketplaces enable row level security;
alter table public.orders enable row level security;
alter table public.order_details enable row level security;
alter table public.imports enable row level security;
alter table public.import_details enable row level security;
alter table public.finance_1st enable row level security;
alter table public.finance_2nd enable row level security;
alter table public.matching_lists enable row level security;
alter table public.item_stocks enable row level security;
alter table public.listing_ids enable row level security;
alter table public.listing_links enable row level security;
alter table public.monthly_summary enable row level security;
alter table public.detailed_result enable row level security;
alter table public.packaging_type_list enable row level security;
alter table public.customer_management enable row level security;
