create extension if not exists pgcrypto;

create or replace function public.warehouse_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.items (
  code text primary key,
  name text not null default '',
  volume_width numeric(12, 2) not null default 0,
  volume_length numeric(12, 2) not null default 0,
  volume_height numeric(12, 2) not null default 0,
  location_code text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.warehouse_racks (
  rack_code text not null,
  item_code text not null references public.items(code) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (rack_code, item_code)
);

create table if not exists public.daily_stock (
  sku_cd text not null references public.items(code) on delete cascade,
  stock_date date not null,
  stock_cnt_real integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (sku_cd, stock_date)
);

create table if not exists public.warehouse_movements (
  id bigint generated by default as identity primary key,
  movement_type text not null check (movement_type in ('inbound', 'outbound', 'move', 'set_location')),
  item_code text not null references public.items(code) on delete cascade,
  rack_code text,
  from_rack text,
  to_rack text,
  quantity integer not null default 0,
  note text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists items_location_code_idx
  on public.items (location_code);

create index if not exists warehouse_racks_item_code_idx
  on public.warehouse_racks (item_code);

create index if not exists daily_stock_sku_latest_idx
  on public.daily_stock (sku_cd, stock_date desc);

drop trigger if exists items_set_updated_at on public.items;
create trigger items_set_updated_at
before update on public.items
for each row
execute function public.warehouse_set_updated_at();

drop trigger if exists warehouse_racks_set_updated_at on public.warehouse_racks;
create trigger warehouse_racks_set_updated_at
before update on public.warehouse_racks
for each row
execute function public.warehouse_set_updated_at();

alter table public.items enable row level security;
alter table public.warehouse_racks enable row level security;
alter table public.daily_stock enable row level security;
alter table public.warehouse_movements enable row level security;

create or replace function public.warehouse_row_bays(p_row_label text)
returns integer
language sql
immutable
as $$
  select case upper(trim(coalesce(p_row_label, '')))
    when 'SR1' then 21
    when 'SR2' then 11
    when 'SR3' then 21
    else 0
  end
$$;

create or replace function public.warehouse_row_levels(p_row_label text)
returns integer
language sql
immutable
as $$
  select case upper(trim(coalesce(p_row_label, '')))
    when 'SR1' then 3
    when 'SR2' then 6
    when 'SR3' then 3
    else 0
  end
$$;

create or replace function public.warehouse_level_height(p_level integer)
returns integer
language sql
immutable
as $$
  select case coalesce(p_level, 0)
    when 1 then 120
    when 2 then 100
    when 3 then 180
    when 4 then 100
    when 5 then 100
    when 6 then 100
    else 100
  end
$$;

create or replace function public.warehouse_level_capacity(p_level integer)
returns integer
language sql
immutable
as $$
  select 110 * 110 * public.warehouse_level_height(p_level)
$$;

create or replace function public.warehouse_sr2_level_to_letter(p_level integer)
returns text
language plpgsql
immutable
as $$
begin
  if p_level is null or p_level < 1 or p_level > 6 then
    raise exception 'Invalid SR2 level: %', p_level;
  end if;
  return chr(65 + (6 - p_level));
end;
$$;

create or replace function public.warehouse_sr2_letter_to_level(p_letter text)
returns integer
language plpgsql
immutable
as $$
declare
  v_letter text := upper(left(trim(coalesce(p_letter, '')), 1));
begin
  if v_letter < 'A' or v_letter > 'F' then
    raise exception 'Invalid SR2 level letter: %', p_letter;
  end if;
  return 6 - (ascii(v_letter) - ascii('A'));
end;
$$;

create or replace function public.warehouse_cell_code(p_row_label text, p_bay integer, p_level integer)
returns text
language plpgsql
immutable
as $$
declare
  v_row text := upper(trim(coalesce(p_row_label, '')));
begin
  if v_row = 'SR2' then
    return format('SR2-%s-%s', public.warehouse_sr2_level_to_letter(p_level), lpad(p_bay::text, 2, '0'));
  end if;

  return format('%s-%s-%s', v_row, lpad(p_bay::text, 2, '0'), lpad(p_level::text, 2, '0'));
end;
$$;

create or replace function public.warehouse_parse_rack_code(p_code text)
returns table(row_label text, bay integer, level integer)
language plpgsql
immutable
as $$
declare
  s text := upper(trim(coalesce(p_code, '')));
  m text[];
begin
  m := regexp_match(s, '^SR2-([A-F])-([0-9]{2})$');
  if m is not null then
    row_label := 'SR2';
    bay := m[2]::integer;
    level := public.warehouse_sr2_letter_to_level(m[1]);
    return next;
    return;
  end if;

  m := regexp_match(s, '^SR2-([0-9]{2})-([0-9]{2})$');
  if m is not null then
    row_label := 'SR2';
    bay := m[1]::integer;
    level := m[2]::integer;
    return next;
    return;
  end if;

  m := regexp_match(s, '^SR([0-9]{1,2})-([0-9]{2})-([0-9]{2})$');
  if m is not null then
    row_label := format('SR%s', m[1]::integer);
    bay := m[2]::integer;
    level := m[3]::integer;
    return next;
    return;
  end if;

  m := regexp_match(s, '^SR-([0-9]{2})-([A-F])-([0-9]{2})$');
  if m is not null and m[1] = '02' then
    row_label := 'SR2';
    bay := m[3]::integer;
    level := public.warehouse_sr2_letter_to_level(m[2]);
    return next;
    return;
  end if;

  m := regexp_match(s, '^SR-([0-9]{2})-([0-9]{2})-([0-9]{2})$');
  if m is not null then
    row_label := format('SR%s', m[1]::integer);
    bay := m[2]::integer;
    level := m[3]::integer;
    return next;
    return;
  end if;
end;
$$;

create or replace function public.warehouse_to_canonical_code(p_code text)
returns text
language plpgsql
immutable
as $$
declare
  v_row text;
  v_bay integer;
  v_level integer;
begin
  select row_label, bay, level
    into v_row, v_bay, v_level
  from public.warehouse_parse_rack_code(p_code)
  limit 1;

  if v_row is null then
    return trim(coalesce(p_code, ''));
  end if;

  return public.warehouse_cell_code(v_row, v_bay, v_level);
end;
$$;

create or replace function public.warehouse_has_wildcard_00(p_location text)
returns boolean
language plpgsql
immutable
as $$
declare
  v_part text;
  v_parts text[] := string_to_array(public.warehouse_to_canonical_code(p_location), '-');
begin
  if v_parts is null then
    return false;
  end if;

  foreach v_part in array v_parts loop
    if v_part = '00' then
      return true;
    end if;
  end loop;

  return false;
end;
$$;

create or replace function public.warehouse_location_in_use(p_location text, p_ignore_item_code text default null)
returns text
language plpgsql
stable
as $$
declare
  v_location text;
  v_code text;
begin
  if public.warehouse_has_wildcard_00(p_location) then
    return null;
  end if;

  v_location := public.warehouse_to_canonical_code(p_location);

  select code
    into v_code
  from public.items
  where location_code = v_location
    and (p_ignore_item_code is null or code <> p_ignore_item_code)
  limit 1;

  return v_code;
end;
$$;

create or replace function public.warehouse_get_config()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'rows', jsonb_build_array('SR1', 'SR2', 'SR3'),
    'bays', 21,
    'levels', 3,
    'level_heights_cm', jsonb_build_object(
      '1', 120,
      '2', 100,
      '3', 180,
      '4', 100,
      '5', 100,
      '6', 100
    ),
    'rate_low_max', 25,
    'rate_normal_max', 70
  )
$$;

create or replace function public.warehouse_get_items(p_q text default '', p_limit integer default 500)
returns jsonb
language plpgsql
stable
as $$
declare
  v_q text := trim(coalesce(p_q, ''));
  v_limit integer := least(greatest(coalesce(p_limit, 500), 1), 5000);
begin
  return jsonb_build_object(
    'items',
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'code', t.code,
          'name', t.name,
          'w', t.volume_width,
          'l', t.volume_length,
          'h', t.volume_height,
          'unit_cm3', (
            greatest(t.volume_width, 0::numeric) *
            greatest(t.volume_length, 0::numeric) *
            greatest(t.volume_height, 0::numeric)
          )::integer,
          'location', coalesce(t.location_code, '')
        )
        order by t.code, t.name
      )
      from (
        select *
        from public.items i
        where v_q = ''
          or i.code ilike '%' || v_q || '%'
          or i.name ilike '%' || v_q || '%'
          or i.location_code ilike '%' || v_q || '%'
        order by i.code asc, i.name asc
        limit v_limit
      ) t
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.warehouse_get_items_with_stock(p_q text default '', p_limit integer default 300)
returns jsonb
language plpgsql
stable
as $$
declare
  v_q text := trim(coalesce(p_q, ''));
  v_limit integer := least(greatest(coalesce(p_limit, 300), 1), 5000);
begin
  return jsonb_build_object(
    'items',
    coalesce((
      with latest_stock as (
        select distinct on (ds.sku_cd)
          ds.sku_cd,
          ds.stock_cnt_real
        from public.daily_stock ds
        order by ds.sku_cd, ds.stock_date desc
      )
      select jsonb_agg(
        jsonb_build_object(
          'code', t.code,
          'name', t.name,
          'w', t.volume_width,
          'l', t.volume_length,
          'h', t.volume_height,
          'unit_cm3', (
            greatest(t.volume_width, 0::numeric) *
            greatest(t.volume_length, 0::numeric) *
            greatest(t.volume_height, 0::numeric)
          )::integer,
          'location', coalesce(t.location_code, ''),
          'stock_qty', coalesce(ls.stock_cnt_real, 0)
        )
        order by t.code, t.name
      )
      from (
        select *
        from public.items i
        where v_q = ''
          or i.code ilike '%' || v_q || '%'
          or i.name ilike '%' || v_q || '%'
          or i.location_code ilike '%' || v_q || '%'
        order by i.code asc, i.name asc
        limit v_limit
      ) t
      left join latest_stock ls on ls.sku_cd = t.code
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.warehouse_get_cells(p_row text default 'SR1')
returns jsonb
language plpgsql
stable
as $$
declare
  v_row text := upper(trim(coalesce(p_row, 'SR1')));
  v_bays integer := public.warehouse_row_bays(v_row);
  v_levels integer := public.warehouse_row_levels(v_row);
  v_result jsonb;
begin
  if v_bays = 0 or v_levels = 0 then
    raise exception 'Unknown row: %', p_row;
  end if;

  with grid as (
    select
      v_row as row_label,
      b as bay,
      l as level,
      public.warehouse_cell_code(v_row, b, l) as code,
      public.warehouse_level_capacity(l) as capacity_cm3
    from generate_series(1, v_bays) as b
    cross join generate_series(1, v_levels) as l
  ),
  cell_items as (
    select
      public.warehouse_to_canonical_code(sr.rack_code) as rack_code,
      i.code as sku,
      coalesce(i.name, '') as name,
      sr.quantity as qty,
      (
        greatest(coalesce(i.volume_width, 0), 0::numeric) *
        greatest(coalesce(i.volume_length, 0), 0::numeric) *
        greatest(coalesce(i.volume_height, 0), 0::numeric) *
        greatest(sr.quantity, 0)
      )::bigint as used_cm3,
      coalesce(i.location_code, '') as location
    from public.warehouse_racks sr
    join public.items i on i.code = sr.item_code
    join lateral public.warehouse_parse_rack_code(sr.rack_code) pr on true
    where pr.row_label = v_row
  ),
  cell_json as (
    select
      g.bay,
      g.level,
      jsonb_build_object(
        'code', g.code,
        'bay', g.bay,
        'level', g.level,
        'capacity_cm3', g.capacity_cm3,
        'total_cm3', coalesce(sum(ci.used_cm3), 0)::integer,
        'kinds', count(ci.sku)::integer,
        'items', coalesce(
          jsonb_agg(
            jsonb_build_object(
              'sku', ci.sku,
              'name', ci.name,
              'qty', ci.qty,
              'used_cm3', ci.used_cm3,
              'location', ci.location
            )
            order by ci.used_cm3 desc, ci.sku asc
          ) filter (where ci.sku is not null),
          '[]'::jsonb
        )
      ) as payload
    from grid g
    left join cell_items ci on ci.rack_code = g.code
    group by g.code, g.bay, g.level, g.capacity_cm3
    order by g.bay, g.level
  )
  select jsonb_build_object(
    'row', v_row,
    'bays', v_bays,
    'levels', v_levels,
    'cells', coalesce(jsonb_agg(payload order by bay, level), '[]'::jsonb)
  )
    into v_result
  from cell_json;

  return v_result;
end;
$$;

create or replace function public.warehouse_search_racks(p_q text default '', p_limit integer default 500)
returns jsonb
language plpgsql
stable
as $$
declare
  v_q text := trim(coalesce(p_q, ''));
  v_limit integer := least(greatest(coalesce(p_limit, 500), 1), 5000);
  v_canon text := public.warehouse_to_canonical_code(v_q);
begin
  return jsonb_build_object(
    'q', v_q,
    'results',
    coalesce((
      with rows_ as (
        select
          public.warehouse_to_canonical_code(sr.rack_code) as rack_code,
          pr.row_label,
          pr.bay,
          pr.level,
          i.code as sku,
          coalesce(i.name, '') as name,
          sr.quantity as qty,
          coalesce(i.location_code, '') as location,
          (
            greatest(coalesce(i.volume_width, 0), 0::numeric) *
            greatest(coalesce(i.volume_length, 0), 0::numeric) *
            greatest(coalesce(i.volume_height, 0), 0::numeric) *
            greatest(sr.quantity, 0)
          )::integer as used_cm3,
          public.warehouse_level_capacity(pr.level) as capacity_cm3
        from public.warehouse_racks sr
        join public.items i on i.code = sr.item_code
        join lateral public.warehouse_parse_rack_code(sr.rack_code) pr on true
        where v_q = ''
          or i.code ilike '%' || v_q || '%'
          or i.name ilike '%' || v_q || '%'
          or i.location_code ilike '%' || v_q || '%'
          or public.warehouse_to_canonical_code(sr.rack_code) ilike '%' || v_q || '%'
          or public.warehouse_to_canonical_code(sr.rack_code) ilike '%' || v_canon || '%'
        order by public.warehouse_to_canonical_code(sr.rack_code) asc, i.code asc
        limit v_limit
      )
      select jsonb_agg(
        jsonb_build_object(
          'rack_code', t.rack_code,
          'row', t.row_label,
          'bay', t.bay,
          'level', t.level,
          'sku', t.sku,
          'name', t.name,
          'qty', t.qty,
          'capacity_cm3', t.capacity_cm3,
          'used_cm3', t.used_cm3,
          'rate', case
            when t.capacity_cm3 <= 0 then 0
            else floor((t.used_cm3::numeric / t.capacity_cm3::numeric) * 100)::integer
          end,
          'location', t.location
        )
      )
      from rows_ t
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.warehouse_post_inbound(p_rack_code text, p_item_code text, p_qty integer)
returns jsonb
language plpgsql
as $$
declare
  v_rack text := public.warehouse_to_canonical_code(p_rack_code);
  v_row text;
  v_bay integer;
  v_level integer;
begin
  if coalesce(p_qty, 0) <= 0 then
    raise exception 'qty must be greater than 0';
  end if;

  if not exists (select 1 from public.items where code = p_item_code) then
    raise exception 'Unknown item_code: %', p_item_code;
  end if;

  select row_label, bay, level
    into v_row, v_bay, v_level
  from public.warehouse_parse_rack_code(v_rack)
  limit 1;

  if v_row is null then
    raise exception 'Invalid rack code: %', p_rack_code;
  end if;

  insert into public.warehouse_racks (rack_code, item_code, quantity)
  values (v_rack, p_item_code, p_qty)
  on conflict (rack_code, item_code)
  do update set quantity = public.warehouse_racks.quantity + excluded.quantity;

  insert into public.warehouse_movements (movement_type, item_code, rack_code, quantity, note)
  values ('inbound', p_item_code, v_rack, p_qty, '');

  return jsonb_build_object(
    'ok', true,
    'row', v_row,
    'cells', public.warehouse_get_cells(v_row)
  );
end;
$$;

create or replace function public.warehouse_post_outbound(p_rack_code text, p_item_code text, p_qty integer)
returns jsonb
language plpgsql
as $$
declare
  v_rack text := public.warehouse_to_canonical_code(p_rack_code);
  v_row text;
  v_bay integer;
  v_level integer;
  v_current integer;
begin
  if coalesce(p_qty, 0) <= 0 then
    raise exception 'qty must be greater than 0';
  end if;

  select row_label, bay, level
    into v_row, v_bay, v_level
  from public.warehouse_parse_rack_code(v_rack)
  limit 1;

  if v_row is null then
    raise exception 'Invalid rack code: %', p_rack_code;
  end if;

  select quantity
    into v_current
  from public.warehouse_racks
  where rack_code = v_rack
    and item_code = p_item_code
  for update;

  if coalesce(v_current, 0) < p_qty then
    raise exception 'Not enough quantity in rack';
  end if;

  update public.warehouse_racks
  set quantity = quantity - p_qty
  where rack_code = v_rack
    and item_code = p_item_code;

  delete from public.warehouse_racks
  where rack_code = v_rack
    and item_code = p_item_code
    and quantity <= 0;

  insert into public.warehouse_movements (movement_type, item_code, rack_code, quantity, note)
  values ('outbound', p_item_code, v_rack, p_qty, '');

  return jsonb_build_object(
    'ok', true,
    'row', v_row,
    'cells', public.warehouse_get_cells(v_row)
  );
end;
$$;

create or replace function public.warehouse_post_move(p_from_rack text, p_to_rack text, p_item_code text, p_qty integer)
returns jsonb
language plpgsql
as $$
declare
  v_from text := public.warehouse_to_canonical_code(p_from_rack);
  v_to text := public.warehouse_to_canonical_code(p_to_rack);
  v_from_row text;
  v_from_bay integer;
  v_from_level integer;
  v_to_row text;
  v_to_bay integer;
  v_to_level integer;
  v_current integer;
  v_rows jsonb;
begin
  if coalesce(p_qty, 0) <= 0 then
    raise exception 'qty must be greater than 0';
  end if;

  if v_from = v_to then
    raise exception 'from_rack and to_rack must differ';
  end if;

  select row_label, bay, level
    into v_from_row, v_from_bay, v_from_level
  from public.warehouse_parse_rack_code(v_from)
  limit 1;

  select row_label, bay, level
    into v_to_row, v_to_bay, v_to_level
  from public.warehouse_parse_rack_code(v_to)
  limit 1;

  if v_from_row is null then
    raise exception 'Invalid from_rack: %', p_from_rack;
  end if;

  if v_to_row is null then
    raise exception 'Invalid to_rack: %', p_to_rack;
  end if;

  select quantity
    into v_current
  from public.warehouse_racks
  where rack_code = v_from
    and item_code = p_item_code
  for update;

  if coalesce(v_current, 0) < p_qty then
    raise exception 'Not enough quantity in source rack';
  end if;

  update public.warehouse_racks
  set quantity = quantity - p_qty
  where rack_code = v_from
    and item_code = p_item_code;

  delete from public.warehouse_racks
  where rack_code = v_from
    and item_code = p_item_code
    and quantity <= 0;

  insert into public.warehouse_racks (rack_code, item_code, quantity)
  values (v_to, p_item_code, p_qty)
  on conflict (rack_code, item_code)
  do update set quantity = public.warehouse_racks.quantity + excluded.quantity;

  insert into public.warehouse_movements (movement_type, item_code, from_rack, to_rack, quantity, note)
  values ('move', p_item_code, v_from, v_to, p_qty, '');

  if v_from_row = v_to_row then
    v_rows := jsonb_build_object(
      v_from_row, public.warehouse_get_cells(v_from_row)
    );
  else
    v_rows := jsonb_build_object(
      v_from_row, public.warehouse_get_cells(v_from_row),
      v_to_row, public.warehouse_get_cells(v_to_row)
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'rows', v_rows
  );
end;
$$;

create or replace function public.warehouse_post_set_location(p_item_code text, p_location text)
returns jsonb
language plpgsql
as $$
declare
  v_location text;
  v_used_by text;
begin
  if trim(coalesce(p_item_code, '')) = '' then
    raise exception 'item_code is required';
  end if;

  if not exists (select 1 from public.items where code = p_item_code) then
    raise exception 'Unknown item_code: %', p_item_code;
  end if;

  if trim(coalesce(p_location, '')) = '00' then
    update public.items
    set location_code = '00'
    where code = p_item_code;

    insert into public.warehouse_movements (movement_type, item_code, quantity, note)
    values ('set_location', p_item_code, 0, '00');

    return jsonb_build_object('ok', true);
  end if;

  v_location := public.warehouse_to_canonical_code(p_location);
  v_used_by := public.warehouse_location_in_use(v_location, p_item_code);

  if v_used_by is not null then
    raise exception 'Location code already in use by %', v_used_by;
  end if;

  update public.items
  set location_code = v_location
  where code = p_item_code;

  insert into public.warehouse_movements (movement_type, item_code, quantity, note)
  values ('set_location', p_item_code, 0, v_location);

  return jsonb_build_object('ok', true);
end;
$$;
