-- 품절방지프로젝트 ownerclan_options 테이블 추가
create table if not exists public.ownerclan_options (
  id           bigint generated by default as identity primary key,
  base_code    text    not null,
  option_index integer not null,
  option_key   text    not null,
  option_json  text    not null,
  updated_at   timestamptz default now(),
  constraint uq_ownerclan_base_idx unique (base_code, option_index)
);

create index if not exists idx_ownerclan_base_code
  on public.ownerclan_options (base_code);

alter table public.ownerclan_options enable row level security;
